### ISSUE TITLE
Noob help

### ISSUE THREAD

**Issue by twobob** [hytromo/MacroPolo#1]
Although the library is indeed nicely documented.

Some of us are python noobs... Okay "me".

Just a couple of examples of pixel searching, looping, and clicking based on previous results would go a long way to make this more understandable to the average noob.

Much obliged for your consideration.

**Comment by twobob** [comment]
I know this is a noob error but...

here is an example: "me.py"

```
#!/usr/bin/python

import macropolo
macro = macropolo.Macro()
area = [300,300,500,340]

if __name__ == '__main__':
    count = macro.pixel_color_in_area_counter(area, "#c41102")

    point = macro.wait_for_pixel_color_in_area(area, "#c41102", 8000)
    print count
    print point
```

me@computer /usr/local/src $ python ./me.py 

Traceback (most recent call last):
  File "./me.py", line 14, in <module>
    point = macro.wait_for_pixel_color_in_area(area, "#c41102", 8000)
  File "/usr/local/lib/python2.7/dist-packages/macropolo.py", line 262, in wait_for_pixel_color_in_area
    exists, point = pixel_color_in_area(rectangle, color)
NameError: global name 'pixel_color_in_area' is not defined

I must be doing the import wrong or something? but I am failing to work it out???

**Comment by hytromo** [comment]
Hello twobob and thanks for your interest for my library.

The library was actually Class-free, but it was suggested to make it
class"able".

After making it class"able" (which means you will have to create an object
of the class to call functions) I didn't do much of testing.

The error you see is a bug from inside the library. I will try to correct
it as soon as possible and upload the correct version :)

**Comment by twobob** [comment]
okay thanks. :)

I added a very crappy bit of mouse moving... (slide_cursor_to)

I totally suck at python (this would be my first go)

but will arrange a pull if it seems worthwhile.

Much obliged.

**Comment by twobob** [comment]
https://github.com/twobob/MacroPolo/commit/c23234c1475ab16676aa78c6c86e2bbe1f1536b9

it's pretty horrible...

but seems to work marginally well...

**Comment by hytromo** [comment]
Nice. Don't be too harsh to yourself. I don't know python well myself. I
only know kind of well C++.

I suck very hard at using git, thought. Can you please tell me how to merge
your new function to my already existent branch?

**Comment by hytromo** [comment]
Anyway, I found some time and fixed the code. I think everything should be
working fine now.

**Comment by cmoang** [comment]
Have never tried before python, but the library's comments seem extremely helpful.

I notice you used `import macropolo`. After downloading the file, what do I have to do in order to get it work in an Ubuntu/GNU Linux system? In other words, how do I install the library? I tried with `pip install macropolo` but this does not work.  Thanks!

**Comment by hytromo** [comment]
Hey there :) You must download the file and put it into the directory of
your Python script. Then, in your script you must use

import macropolo

and then you will be able to use the library's functions :) Oh, but don't
forget to install the required packages before using it!

If you need further help on how to use the library, please don't hesitate
to reply back!

**Comment by cmoang** [comment]
Hi again, I know it isn't your job to learn me how to work with `macropolo.py`, but I'll ask anyway :)
I want to write a simple python script (totally noob in python) that uses your function `wait_for_pixel_color_in_area` . But I get:

``` bash
$ python ./test.py 
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    wait_for_pixel_color_in_area(self, [100, 100, 600, 300], FFFFFF, 10)
NameError: name 'wait_for_pixel_color_in_area' is not defined
```

The script is exactly this:

``` python
#!/usr/bin/python -W ignore::DeprecationWarning
import macropolo
wait_for_pixel_color_in_area(self, [100, 100, 600, 300], FFFFFF, 10)
```

What am I doing wrong? 

Thanks!

**Comment by hytromo** [comment]
Hello cmoang and sorry for the late reply.

As you can see in the code example here:
http://melloristudio.com/macropolo#downloads you will have to initialize an
object of class Macro first and then call the functions with it.'

If my reply wasn't really helpful, inform me and I will try to elaborate.

On Wed, Oct 1, 2014 at 1:29 AM, cmoang notifications@github.com wrote:

> Hi again, I know it isn't your job to learn me how to work with
> macropolo.py, but I'll ask anyway :)
> I want to write a simple python script (totally noob in python) that uses
> your function wait_for_pixel_color_in_area . But I get:
> 
> $ python ./test.py
> Traceback (most recent call last):
>   File "./test.py", line 5, in <module>
>     wait_for_pixel_color_in_area(self, [100, 100, 600, 300], FFFFFF, 10)
> NameError: name 'wait_for_pixel_color_in_area' is not defined
> 
> The script is exactly this:
> 
> #!/usr/bin/python -W ignore::DeprecationWarningimport macropolowait_for_pixel_color_in_area(self, [100, 100, 600, 300], FFFFFF, 10)
> 
> What am I doing wrong?
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/hakermania/MacroPolo/issues/1#issuecomment-57393282.

##
